# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_submodules

pkg_resources_vendor = collect_submodules(
    "pkg_resources._vendor",
    filter=lambda name: name != "pkg_resources._vendor.pyparsing.diagram",
)

analysis = Analysis(
    ["atomic_app.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        "numpy",
        "scipy",
        "scipy.ndimage",
        "scipy.optimize",
        "scipy.spatial",
        "scipy.stats",
        "matplotlib",
        "matplotlib.backends.backend_tkagg",
        "tifffile",
        "PIL",
        "PIL.Image",
        "PIL.ImageColor",
        "PIL.ImageDraw",
        "PIL.ImageFont",
        "atomic_core",
    ] + pkg_resources_vendor,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=["hook_numpy_fix.py"],
    excludes=[
        "pytest",
        "_pytest",
        "IPython",
        "jedi",
        "pandas",
        "openpyxl",
        "dask",
        "distributed",
        "numba",
        "llvmlite",
        "h5py",
        "zarr",
        "boto3",
        "botocore",
        "keyring",
        "cryptography",
        "lxml",
        "conda",
        "pythoncom",
        "pywin32",
        "win32com",
        "win32api",
        "win32evtlogutil",
        "win32evtlog",
        "win32pdh",
        "win32con",
        "winerror",
        "pywintypes",
        "_win32sysloader",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(analysis.pure)

exe = EXE(
    pyz,
    analysis.scripts,
    analysis.binaries,
    analysis.datas,
    [],
    name="原子识别与强度分析工具v1.3",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
